<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <PublishUrl>publish\</PublishUrl>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <None Update="Employees.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*" />
        <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*" />
        <PackageReference Include="DevExpress.Win.RichEdit" Version="24.2.*" />
    </ItemGroup>
</Project>